name: "Hello Wrapper Action"
description: "Wraps github-script to say hello"
inputs:
  name:
    description: "Name to greet"
    required: true
outputs:
  message:
    description: "Greeting message"
    value: ${{ steps.say.outputs.message }}
runs:
  using: "composite"
  steps:
    - name: Say hello
      id: say
      uses: actions/github-script@v7
      with:
        script: |
          const name = "${{ inputs.name }}";
          const message = `🎉 Hello from wrapped action, ${name}!`;
          core.setOutput("message", message)
