name: "Hello Wrapper Action"
description: "Wraps github-script to say hello"
inputs:
  name:
    description: "Name to greet"
    required: true
outputs:
  message:
    description: "Greeting message"
runs:
  using: "composite"
  steps:
    - name: Run GitHub Script
      uses: actions/github-script@v7
      with:
        script: |
          const name = "${{ inputs.name }}";
          const message = `Hello from wrapped action, ${name}!`;
          core.setOutput("message", message);

    - name: Forward output
      run: 'echo "message=${{ steps.github-script.outputs.message }}"'
